name: Run Behat Tests

on:
  workflow_call:  # ← Añade esto para permitir que otros workflows lo llamen
  push:
    branches:
      - dev
    paths:
      - 'tests/features/**'
      - 'behat.yml'
      - 'composer.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - run: rm -f composer.lock
    - run: composer install --no-cache
    - run: composer dump-autoload
    - run: vendor/bin/behat
      env:
        DEV_USER: ${{ secrets.DEV_USER }}
        DEV_PASSWORD: ${{ secrets.DEV_PASSWORD }}